// apps/dev/nuxt/components/Header.vue
<script setup lang="ts">
const { signIn, signOut, session, auth } = useAuth()

const password = ref("")

async function getProtectedRoute() {
  const data = await $fetch("/api/protected")

  alert(data?.message ?? "No data returned")
}
</script>

<template>
  <header>
    <nav class="nojs-show loaded">
      <div class="nav-left">
        <img
          alt="Avatar"
          :src="
            session?.user?.image ??
            'https://api.dicebear.com/9.x/thumbs/svg?seed=234173&randomizeIds=true'
          "
          class="avatar"
        />
      </div>
      <div class="nav-right">
        <template v-if="session">
          <span class="header-text">
            <small>Signed in as</small><br />
            <strong>
              {{
                auth.loggedIn
                  ? (auth.user.email ?? auth.user.name)
                  : "unauthenticated"
              }}
            </strong>
          </span>
          <div class="buttonPrimary" @click="signOut()">Sign out</div>
        </template>
        <template v-else>
          <span class="header-text"
            >Status:
            {{ auth.loggedIn ? "authenticated" : "unauthenticated" }}</span
          >
          <span class="header-text">You are not signed in</span>
          <div class="buttonPrimary">Sign in</div>
        </template>
      </div>
    </nav>
    <div class="links">
      <NuxtLink class="linkItem" href="/">Home</NuxtLink>
      <NuxtLink class="linkItem" href="/protected">Protected</NuxtLink>
      <NuxtLink class="linkItem" href="/guest">Guest</NuxtLink>
      <div class="linkItem" @click="getProtectedRoute">Call Protected API</div>
    </div>
  </header>
</template>

// apps/dev/sveltekit/src/components/header.svelte
<script lang="ts">
  import { page } from "$app/stores"
  import { SignIn, SignOut } from "@auth/sveltekit/components"
</script>

<header>
  <nav class="nojs-show loaded">
    <div class="nav-left">
      <img
        alt="Avatar"
        src={$page.data.session?.user?.image ??
          `https://api.dicebear.com/9.x/thumbs/svg?seed=${Math.floor(Math.random() * 100000) + 1}&randomizeIds=true`}
        class="avatar"
      />
    </div>
    <div class="nav-right">
      {#if $page.data.session}
        <span class="header-text">
          <small>Signed in as</small><br />
          <strong>
            {$page.data.session.user?.email ?? $page.data.session.user?.name}
          </strong>
        </span>
        <SignOut>
          <div class="buttonPrimary" slot="submitButton">Sign out</div>
        </SignOut>
      {:else}
        <span class="header-text">You are not signed in</span>
        <SignIn>
          <div class="buttonPrimary" slot="submitButton">Sign in</div>
        </SignIn>
      {/if}
    </div>
  </nav>
  <div class="links">
    <a class="linkItem" href="/">Home</a>
    <a class="linkItem" href="/protected">Protected</a>
  </div>
</header>
