// apps/examples/nextjs/components/header.tsx
import type { Session } from "next-auth"
import Link from "next/link"
import styles from "./header.module.css"

export function Header({
  session,
  signIn,
  signOut,
}: {
  session: Session | null
  signIn: any
  signOut: any
}) {
  return (
    <header>
      <div className={styles.signedInStatus}>
        {!session?.user && (
          <>
            <span className={styles.notSignedInText}>
              You are not signed in
            </span>
            {signIn}
          </>
        )}
        {session?.user && (
          <>
            {session.user?.image && (
              <img src={session.user.image} className={styles.avatar} />
            )}
            <span className={styles.signedInText}>
              <small>Signed in as</small>
              <br />
              <strong>{session.user?.email} </strong>
              {session.user?.name ? `(${session.user.name})` : null}
            </span>
            {signOut}
          </>
        )}
      </div>
      <nav>
        <ul className={styles.navItems}>
          <li className={styles.navItem}>
            <Link href="/">Home (app)</Link>
          </li>
          <li className={styles.navItem}>
            <Link href="/dashboard">Dashboard (app)</Link>
          </li>
          <li className={styles.navItem}>
            <Link href="/policy">Policy (pages)</Link>
          </li>
          <li className={styles.navItem}>
            <Link href="/credentials">Credentials (pages)</Link>
          </li>
          <li className={styles.navItem}>
            <Link href="/protected-ssr">getServerSideProps (pages)</Link>
          </li>
          <li className={styles.navItem}>
            <Link href="/api/examples/protected">API Route (pages)</Link>
          </li>
        </ul>
      </nav>
    </header>
  )
}

// apps/dev/sveltekit/src/components/header.svelte
<script lang="ts">
  import { page } from "$app/stores"
  import { SignIn, SignOut } from "@auth/sveltekit/components"
</script>

<header>
  <nav class="nojs-show loaded">
    <div class="nav-left">
      <img
        src={$page.data.session?.user?.image ??
          "https://source.boringavatars.com/beam/120"}
        class="avatar"
      />
    </div>
    <div class="nav-right">
      {#if $page.data.session}
        <span class="header-text">
          <small>Signed in as</small><br />
          <strong>
            {$page.data.session.user?.email ?? $page.data.session.user?.name}
          </strong>
        </span>
        <SignOut>Sign out</SignOut>
      {:else}
        <span class="header-text">You are not signed in</span>
        <SignIn>
          <div class="buttonPrimary" slot="submitButton">Sign in</div>
        </SignIn>
      {/if}
    </div>
  </nav>
  <div class="links">
    <a class="linkItem" href="/">Home</a>
    <a class="linkItem" href="/protected">Protected</a>
  </div>
</header>
