// apps/examples/qwik/src/routes/index.tsx
import { component$ } from "@builder.io/qwik";
import { useSession } from "./plugin@auth";

export default component$(() => {
  const session = useSession();
  return (
    <div class="h-[calc(100vh-5rem)] w-screen bg-slate-100 pt-40 text-center text-2xl">
      <div>This is an example site to demonstrate how to use</div>
      <div class="py-2 font-bold text-blue-600">
        <a target="_blank" href="https://authjs.dev/">
          Auth.js
        </a>
      </div>
      <div>for authentication with</div>
      <div class="py-2 font-bold text-blue-600">
        <a target="_blank" href="https://qwik.dev/">
          Qwik
        </a>
      </div>
      {session.value?.user && (
        <>
          <div class="pt-6 text-2xl font-bold text-slate-800">
            You are logged. Now you can visit
          </div>
          <a class="py-4 font-bold text-blue-600" href="/protected">
            this protected route.
          </a>
        </>
      )}
    </div>
  );
});

// apps/examples/solid-start/src/routes/index.tsx
import { type ParentComponent } from "solid-js"
import { A, Title } from "solid-start"

const Home: ParentComponent = () => {
  return (
    <>
      <Title>Create JD App</Title>
      <div class="flex flex-col gap-2 items-center">
        <h1 class="text-4xl font-bold">SolidStart Auth Example</h1>
        <p class="font-semibold text-md max-w-[40rem]">
          This is an example site to demonstrate how to use{" "}
          <A
            href="https://start.solidjs.com/getting-started/what-is-solidstart"
            class="text-blue-500 underline font-bold"
          >
            SolidStart
          </A>{" "}
          with{" "}
          <A
            href="https://authjs.dev/reference/solidstart"
            class="text-blue-500 underline font-bold"
          >
            SolidStart Auth
          </A>{" "}
          for authentication.
        </p>
      </div>
    </>
  )
}

export default Home
