// packages/next-auth/src/core/pages/signout.tsx
import { Theme } from "../.."

export interface SignoutProps {
  url: URL
  csrfToken: string
  theme: Theme
}

export default function SignoutPage(props: SignoutProps) {
  const { url, csrfToken, theme } = props

  return (
    <div className="signout">
      {theme.brandColor && (
        <style
          dangerouslySetInnerHTML={{
            __html: `
        :root {
          --brand-color: ${theme.brandColor}
        }
      `,
          }}
        />
      )}
      {theme.buttonText && (
        <style
          dangerouslySetInnerHTML={{
            __html: `
        :root {
          --button-text-color: ${theme.buttonText}
        }
      `,
          }}
        />
      )}
      <div className="card">
        {theme.logo && <img src={theme.logo} alt="Logo" className="logo" />}
        <h1>Signout</h1>
        <p>Are you sure you want to sign out?</p>
        <form action={`${url}/signout`} method="POST">
          <input type="hidden" name="csrfToken" value={csrfToken} />
          <button id="submitButton" type="submit">
            Sign out
          </button>
        </form>
      </div>
    </div>
  )
}

// packages/frameworks-sveltekit/src/lib/components/SignOut.svelte
<script lang="ts">
  import { enhance } from "$app/forms"
  import type { signOut } from "$lib/actions"

  export let className = ""
  export let options: Parameters<typeof signOut>[0] = undefined
  export let signOutPage = "signout"
  
</script>

<form
  method="POST"
  action={`/${signOutPage}`}
  use:enhance
  class={`signOutButton ${className}`}
  {...$$restProps}
>
  {#if options}
    {#if options?.redirect}
      <input type="hidden" name="redirect" value={options.redirect} />
    {/if}
    {#if options?.redirectTo}
      <input type="hidden" name="redirectTo" value={options.redirectTo} />
    {/if}
  {/if}
  <button type="submit">
    <slot name="submitButton">Sign Out</slot>
  </button>
</form>
