// apps/dev/solid/src/routes/index.tsx
import { Header } from "../components/nav"
import { getRequestEvent } from "solid-js/web"

export default function App() {
  const event = getRequestEvent()
  return (
    <main>
      <Header session={event?.locals?.auth} />
      <section class="main">
        <h1>Solid Start Auth Example</h1>
        <p>
          This is an example site to demonstrate how to use{" "}
          <a href="https://start.solidjs.com">Solid Start</a> with{" "}
          <a href="https://solidstart.authjs.dev">Solid Start Auth</a> for
          authentication. The "Sign-in" button in the navigation bar is using
          the client-side methods and will take you to the built-in sign-in page
          with all provider options.
        </p>
        <div class="session">
          <h3>Session</h3>
          <pre>{JSON.stringify(event?.locals?.auth ?? {}, null, 2)}</pre>
        </div>
      </section>
    </main>
  )
}

// apps/dev/sveltekit/src/routes/+page.svelte
<script lang="ts">
  import { page } from "$app/stores"
  import { SignIn } from "@auth/sveltekit/components"
  import { signIn } from "@auth/sveltekit/client"

  let password = ""
</script>

<h1>SvelteKit Auth Example</h1>
<div class="container">
  <p>
    This is an example site to demonstrate how to use
    <a href="https://kit.svelte.dev/">SvelteKit</a>
    with <a href="https://sveltekit.authjs.dev">SvelteKit Auth</a> for authentication.
  </p>

  <div class="session-code">
    <div class="session-code-header">
      <h3>Session</h3>
    </div>
    <div class="session-code-body">
      <pre>
{JSON.stringify($page.data.session, null, 2)}
      </pre>
    </div>
  </div>

  <div class="card">
    <div class="card-header">
      <h3>Server Actions</h3>
    </div>
    <div class="card-body">
      <p>
        These actions are all using the components exported from
        <code>@auth/sveltekit/components</code> to run via form actions.
      </p>
      <div class="actions">
        <SignIn provider="github">
          <span slot="submitButton">Sign In with GitHub</span>
        </SignIn>
        <SignIn provider="discord">
          <span slot="submitButton">Sign In with Discord</span>
        </SignIn>
        <SignIn
          provider="credentials"
          authorizationParams={{
            foo: "bar",
          }}
        >
          <span slot="submitButton">Sign In with Credentials</span>
          <div slot="credentials" class="input-wrapper">
            <label for="server-password">Password</label>
            <input
              type="password"
              id="server-password"
              name="password"
              required
            />
          </div>
        </SignIn>
      </div>
    </div>
  </div>
  <div class="card">
    <div class="card-header">
      <h3>Client Actions</h3>
    </div>
    <div class="card-body">
      <p>
        These actions are all using the methods exported from
        <code>@auth/sveltekit/client</code>
      </p>
      <div class="actions">
        <div class="wrapper-form">
          <button on:click={() => signIn("github")}>Sign In with GitHub</button>
        </div>
        <div class="wrapper-form">
          <button on:click={() => signIn("discord")}
            >Sign In with Discord</button
          >
        </div>
        <div class="wrapper-form">
          <div class="input-wrapper">
            <label for="client-password">Password</label>
            <input
              bind:value={password}
              type="password"
              id="client-password"
              name="password"
              required
            />
          </div>
          <button on:click={() => signIn("credentials", { password })}>
            Sign In with Credentials
          </button>
        </div>
      </div>
    </div>
  </div>
</div>
