// apps/playground-nuxt/playground/components/Footer.vue
<template>
  <footer class="fotter">
    <hr>
    <ul class="navItems">
      <li class="navItem">
        <a href="https://github.com/nextauthjs/next-auth/tree/main/apps/playground-nuxt">Demo GitHub</a>
      </li>
      <li class="navItem">
        <a href="https://next-auth.js.org">Next.js Documentation</a>
      </li>
    </ul>
  </footer>
</template>

<style>
.footer {
margin-top: 2rem;
}

.navItems {
margin-bottom: 1rem;
padding: 0;
list-style: none;
}

.navItem {
display: inline-block;
margin-right: 1rem;
}
</style>

// apps/example-nextjs/components/footer.tsx
import Link from "next/link"
import styles from "./footer.module.css"
import packageJSON from "../package.json"

export default function Footer() {
  return (
    <footer className={styles.footer}>
      <hr />
      <ul className={styles.navItems}>
        <li className={styles.navItem}>
          <a href="https://next-auth.js.org">Documentation</a>
        </li>
        <li className={styles.navItem}>
          <a href="https://www.npmjs.com/package/next-auth">NPM</a>
        </li>
        <li className={styles.navItem}>
          <a href="https://github.com/nextauthjs/next-auth-example">GitHub</a>
        </li>
        <li className={styles.navItem}>
          <Link href="/policy">
            <a>Policy</a>
          </Link>
        </li>
        <li className={styles.navItem}>
          <em>next-auth@{packageJSON.dependencies["next-auth"]}</em>
        </li>
      </ul>
    </footer>
  )
}
