// apps/examples/nextjs/pages/protected.tsx
import { useState, useEffect } from "react"
import { useSession } from "@auth/nextjs/client"
import Layout from "../components/layout"

export default function Page() {
  const { status } = useSession({
    required: true,
  })
  const [content, setContent] = useState()

  // Fetch content from protected route
  useEffect(() => {
    if (status === "loading") return
    const fetchData = async () => {
      const res = await fetch("/api/examples/protected")
      const json = await res.json()
      if (json.content) {
        setContent(json.content)
      }
    }
    fetchData()
  }, [status])

  if (status === "loading") return <Layout>Loading...</Layout>

  // If session exists, display content
  return (
    <Layout>
      <h1>Protected Page</h1>
      <p>
        <strong>{content}</strong>
      </p>
    </Layout>
  )
}

// apps/playground-nuxt/playground/pages/protected.vue
<script setup lang="ts">
import { useSession, useFetch, useLazyFetch } from '#imports'
import AccessDenied from '~/components/AccessDenied.vue'

const { data: session } = useSession()
const { data } = await useLazyFetch('/api/examples/protected', {
  server: false
})
</script>

<template>
  <div>
    <AccessDenied v-if="!session" />
    <template v-else>
      <h1>Protected Page</h1>
      <p><strong>{{ data?.content || "\u00a0" }}</strong></p>
    </template>
  </div>
</template>
