// apps/dev/sveltekit/src/routes/(protected)/protected/+page.svelte
<script lang="ts">
  import { page } from "$app/stores"

  $: user = $page.data.session?.user
</script>

<h1>Protected page</h1>
<p>
  This is a protected content. You can access this content because you are
  signed in.
</p>
<p>Session expiry: {$page.data.session?.expires}</p>
<p>User: {user?.name} ({user?.email})</p>

// apps/playground-nuxt/pages/protected.vue
<script setup lang="ts">
const session = useSession()

definePageMeta({
  middleware: 'auth'
})
</script>

<template>
  <div>
    <h1>Protected Page</h1>
    <p>
      This is a protected content. You can access this content because you are
      signed in.
    </p>
    <p>Session expiry: {{ session?.expires }}</p>
  </div>
</template>
