// apps/examples/sveltekit/src/routes/protected/+page.svelte
<script lang="ts">
  import { page } from "$app/stores"
</script>

{#if $page.data.session}
  <h1>Protected page</h1>
  <p>
    This is a protected content. You can access this content because you are
    signed in.
  </p>
  <p>Session expiry: {$page.data.session?.expires}</p>
{:else}
  <h1>Access Denied</h1>
  <p>
    <a href="/auth/signin"> You must be signed in to view this page </a>
  </p>
{/if}

// apps/dev/nuxt/pages/protected.vue
<script setup lang="ts">
const { session } = useAuth()
</script>
<template>
  <div v-if="session">
    <h1>Protected page</h1>
    <p>
      This is a protected content. You can access this content because you are
      signed in.
    </p>
    <p>Session expiry: {{ session?.expires }}</p>
  </div>
  <div v-else>
    <h1>Access Denied</h1>
    <p>
      <NuxtLink href="/"> You must be signed in to view this page </NuxtLink>
    </p>
  </div>
</template>
