// packages/frameworks-qwik/src/index.ts
/**
 *
 * :::warning
 * `@auth/qwik` is currently experimental. The API _will_ change in the future.
 * :::
 *
 * Qwik Auth is the official Qwik integration for Auth.js.
 * It provides a simple way to add authentication to your Qwik app in a few lines of code.
 *
 * ## Installation
 * ```bash npm2yarn
 * npm install @auth/qwik
 * ```
 *
 * ## Usage
 *
 * ### Provider Configuration
 *
 * Create a `plugin@auth.ts` file in the routes folder
 *
 * import GitHub from "@auth/qwik/providers/github"
 * import { QwikAuth$ } from "@auth/qwik"
 *
 * export const {
 *   onRequest, useSession, useSignIn, useSignOut
 * } = QwikAuth$(() => ({ providers: [GitHub] }))
 *
 * ## Signing in and signing out
 *
 * Sign In via form
 *
 * import { component$ } from '@builder.io/qwik';
 * import { Form } from '@builder.io/qwik-city';
 * import { useSignIn } from '~/routes/plugin@auth';
 *
 * export default component$(() => {
 *   const signIn = useSignIn();
 *   return (
 *     <Form action={signIn}>
 *       <input type="hidden" name="providerId" value="github" />
 *       <input type="hidden" name="options.callbackUrl" value="http://qwik-auth-example.com/dashboard" />
 *       <button>Sign In</button>
 *     </Form>
 *   );
 * });
 *
 * Sign In via code
 *
 * import { component$ } from '@builder.io/qwik';
 * import { useSignIn } from '~/routes/plugin@auth';
 *
 * export default component$(() => {
 *   const signIn = useSignIn();
 *   return (
 *     <button onClick$={() => signIn.submit({ providerId: 'github', options: { callbackUrl: 'http://qwik-auth-example.com/dashboard' } })}>Sign In</button>
 *   );
 * });
 *
 * Sign out via form
 *
 * import { component$ } from '@builder.io/qwik';
 * import { Form } from '@builder.io/qwik-city';
 * import { useSignOut } from '~/routes/plugin@auth';
 *
 * export default component$(() => {
 *   const signOut = useSignOut();
 *   return (
 *     <Form action={signOut}>
 *       <input type="hidden" name="callbackUrl" value="/signedout" />
 *       <button>Sign Out</button>
 *     </Form>
 *   );
 * });
 *
 * Sign out via code
 *
 * import { component$ } from '@builder.io/qwik';
 * import { useSignOut } from '~/routes/plugin@auth';
 *
 * export default component$(() => {
 *   const signOut = useSignOut();
 *   return <button onClick$={() => signOut.submit({ callbackUrl: '/signedout' })}>Sign Out</button>;
 * });
 *
 * ## Managing the session
 *
 * import { component$ } from '@builder.io/qwik';
 * import { useSession } from '~/routes/plugin@auth';
 *
 * export default component$(() => {
 *   const session = useSession();
 *   return <p>{session.value?.user?.email}</p>;
 * });
 *
 * ## Authorization
 *
 * Session data can be accessed via the route event.sharedMap.
 * So a route can be protected and redirect using something like this located in a layout.tsx or page index.tsx:
 *
 * export const onRequest: RequestHandler = (event) => {
 *   const session = event.sharedMap.get("session")
 *   if (!session || new Date(session.expires) < new Date()) {
 *     throw event.redirect(302, `/auth/signin?callbackUrl=${event.url.pathname}`);
 *   }
 * };
 *
 * ```
 *
 * @module @auth/qwik
 */

import type { AuthConfig } from "@auth/core"
import { Auth, isAuthAction, skipCSRFCheck } from "@auth/core"
import { AuthAction, Session } from "@auth/core/types"
import { implicit$FirstArg, type QRL } from "@builder.io/qwik"
import {
  globalAction$,
  routeLoader$,
  z,
  zod$,
  type RequestEventCommon,
} from "@builder.io/qwik-city"
import { EnvGetter } from "@builder.io/qwik-city/middleware/request-handler"
import { isServer } from "@builder.io/qwik/build"
import { parseString, splitCookiesString } from "set-cookie-parser"

/** Configure the {@link QwikAuth$} method. */
export interface QwikAuthConfig extends Omit<AuthConfig, "raw"> {}

export type GetSessionResult = Promise<{ data: Session | null; cookie: any }>

function qwikAuthQrl(
  authOptions: QRL<(ev: RequestEventCommon) => QwikAuthConfig>
) {
  const useSignIn = globalAction$(
    async (
      { providerId, callbackUrl: _callbackUrl, options, authorizationParams },
      req
    ) => {
      const { callbackUrl = _callbackUrl ?? defaultCallbackURL(req), ...rest } =
        options ?? {}

      const isCredentials = providerId === "credentials"

      const authOpts = await authOptions(req)
      setEnvDefaults(req.env, authOpts)
      const body = new URLSearchParams({ callbackUrl: callbackUrl as string })
      Object.entries(rest).forEach(([key, value]) => {
        body.set(key, String(value))
      })

      const baseSignInUrl = `/auth/${isCredentials ? "callback" : "signin"}${
        providerId ? `/${providerId}` : ""
      }`
      const signInUrl = `${baseSignInUrl}?${new URLSearchParams(
        authorizationParams
      )}`

      const data = await authAction(body, req, signInUrl, authOpts)

      // set authjs.callback-url cookie. Fix for https://github.com/QwikDev/qwik/issues/5227
      req.cookie.set("authjs.callback-url", callbackUrl, {
        path: "/",
      })

      if (data.url) {
        throw req.redirect(301, data.url)
      }
    },
    zod$({
      providerId: z.string().optional(),
      callbackUrl: z.string().optional(),
      options: z
        .object({
          callbackUrl: z.string(),
        })
        .passthrough()
        .partial()
        .optional(),
      authorizationParams: z
        .union([z.string(), z.custom<URLSearchParams>(), z.record(z.string())])
        .optional(),
    })
  )

  const useSignOut = globalAction$(
    async ({ callbackUrl }, req) => {
      callbackUrl ??= defaultCallbackURL(req)
      const authOpts = await authOptions(req)
      setEnvDefaults(req.env, authOpts)
      const body = new URLSearchParams({ callbackUrl })
      await authAction(body, req, `/auth/signout`, authOpts)
    },
    zod$({
      callbackUrl: z.string().optional(),
    })
  )

  const useSession = routeLoader$((req) => {
    return req.sharedMap.get("session") as Session | null
  })

  const onRequest = async (req: RequestEventCommon) => {
    if (isServer) {
      const prefix: string = "/auth"

      const action = req.url.pathname
        .slice(prefix.length + 1)
        .split("/")[0] as AuthAction

      const authOpts = await authOptions(req)
      setEnvDefaults(req.env, authOpts)
      if (isAuthAction(action) && req.url.pathname.startsWith(prefix + "/")) {
        const res = (await Auth(req.request, authOpts)) as Response
        const cookie = res.headers.get("set-cookie")
        if (cookie) {
          req.headers.set("set-cookie", cookie)
          res.headers.delete("set-cookie")
          fixCookies(req)
        }
        throw req.send(res)
      } else {
        const { data, cookie } = await getSessionData(req.request, authOpts)
        req.sharedMap.set("session", data)
        if (cookie) {
          req.headers.set("set-cookie", cookie)
          fixCookies(req)
        }
      }
    }
  }

  return { useSignIn, useSignOut, useSession, onRequest }
}

/**
 *  Initialize Qwik Auth.
 *
 *  @example
 * ```ts title="plugin@auth.ts"
 * import { QwikAuth } from "@auth/qwik"
 * import GitHub from "@auth/qwik/providers/github"
 *
 * export const {
 *   onRequest, useSession, useSignIn, useSignOut
 * } = QwikAuth$(() => ({ providers: [GitHub] }))
 * ```
 */
export const QwikAuth$ = /*#__PURE__*/ implicit$FirstArg(qwikAuthQrl)

async function authAction(
  body: URLSearchParams | undefined,
  req: RequestEventCommon,
  path: string,
  authOptions: QwikAuthConfig
) {
  const request = new Request(new URL(path, req.request.url), {
    method: req.request.method,
    headers: req.request.headers,
    body: body,
  })
  request.headers.set("content-type", "application/x-www-form-urlencoded")
  const res = (await Auth(request, authOptions)) as Response

  const cookies: string[] = []
  res.headers.forEach((value, key) => {
    if (key === "set-cookie") {
      // while browsers would support setting multiple cookies, the fetch implementation does not, so we join them later.
      cookies.push(value)
    } else if (!req.headers.has(key)) {
      req.headers.set(key, value)
    }
  })

  if (cookies.length > 0) {
    req.headers.set("set-cookie", cookies.join(", "))
  }

  fixCookies(req)

  try {
    return await res.json()
  } catch (error) {
    return await res.text()
  }
}

const fixCookies = (req: RequestEventCommon) => {
  req.headers.set("set-cookie", req.headers.get("set-cookie") || "")
  const cookie = req.headers.get("set-cookie")
  if (cookie) {
    req.headers.delete("set-cookie")
    splitCookiesString(cookie).forEach((cookie) => {
      const { name, value, ...rest } = parseString(cookie)
      req.cookie.set(name, value, rest as any)
    })
  }
}

const defaultCallbackURL = (req: RequestEventCommon) => {
  req.url.searchParams.delete("qaction")
  return req.url.href
}

async function getSessionData(
  req: Request,
  options: AuthConfig
): GetSessionResult {
  options.secret ??= process.env.AUTH_SECRET
  options.trustHost ??= true

  const url = new URL("/auth/session", req.url)
  const response = (await Auth(
    new Request(url, { headers: req.headers }),
    options
  )) as Response

  const { status = 200 } = response

  const data = await response.json()
  const cookie = response.headers.get("set-cookie")
  if (!data || !Object.keys(data).length) {
    return { data: null, cookie }
  }
  if (status === 200) {
    return { data, cookie }
  }

  throw new Error(data.message)
}

export const setEnvDefaults = (env: EnvGetter, config: AuthConfig) => {
  config.basePath = "/auth"
  if (!config.secret?.length) {
    config.secret = []
    const secret = env.get("AUTH_SECRET")
    if (secret) {
      config.secret.push(secret)
    }
    for (const i of [1, 2, 3]) {
      const secret = env.get(`AUTH_SECRET_${i}`)
      if (secret) {
        config.secret.unshift(secret)
      }
    }
  }

  config.redirectProxyUrl ??= env.get("AUTH_REDIRECT_PROXY_URL")
  config.trustHost ??= !!(
    env.get("AUTH_URL") ??
    env.get("AUTH_TRUST_HOST") ??
    env.get("VERCEL") ??
    env.get("CF_PAGES") ??
    env.get("NODE_ENV") !== "production"
  )
  config.skipCSRFCheck = skipCSRFCheck

  config.providers = config.providers.map((p) => {
    const finalProvider = typeof p === "function" ? p({}) : p
    const ID = finalProvider.id.toUpperCase().replace(/-/g, "_")
    if (finalProvider.type === "oauth" || finalProvider.type === "oidc") {
      finalProvider.clientId ??= env.get(`AUTH_${ID}_ID`)
      finalProvider.clientSecret ??= env.get(`AUTH_${ID}_SECRET`)
      if (finalProvider.type === "oidc") {
        finalProvider.issuer ??= env.get(`AUTH_${ID}_ISSUER`)
      }
    } else if (finalProvider.type === "email") {
      finalProvider.apiKey ??= env.get(`AUTH_${ID}_KEY`)
    }
    return finalProvider
  })
}

// packages/frameworks-solid-start/src/index.ts
/**
 *
 * :::warning
 * `@auth/solid-start` is currently experimental. The API _will_ change in the future.
 * :::
 *
 * SolidStart Auth is the official SolidStart integration for Auth.js.
 * It provides a simple way to add authentication to your SolidStart app in a few lines of code.
 *
 * ## Installation
 *
 * ```bash npm2yarn
 * npm install @auth/core @auth/solid-start
 * ```
 *
 * @module @auth/solid-start
 */

import { Auth } from "@auth/core"
import type { AuthAction, AuthConfig, Session } from "@auth/core/types"

export { AuthError, CredentialsSignin } from "@auth/core/errors"
export type {
  Account,
  DefaultSession,
  Profile,
  Session,
  User,
} from "@auth/core/types"

export interface SolidAuthConfig extends AuthConfig {
  /**
   * Defines the base path for the auth routes.
   * @default '/api/auth'
   */
  prefix?: string
}

const actions: AuthAction[] = [
  "providers",
  "session",
  "csrf",
  "signin",
  "signout",
  "callback",
  "verify-request",
  "error",
]

function SolidAuthHandler(prefix: string, authOptions: SolidAuthConfig) {
  return async (event: any) => {
    const { request } = event
    const url = new URL(request.url)
    const action = url.pathname
      .slice(prefix.length + 1)
      .split("/")[0] as AuthAction

    if (!actions.includes(action) || !url.pathname.startsWith(prefix + "/")) {
      return
    }

    return await Auth(request, authOptions)
  }
}

/**
 * ## Setup
 *
 * [Generate an auth secret](https://generate-secret.vercel.app/32), then set it as an environment variable:
 *
 * ```
 * AUTH_SECRET=your_auth_secret
 * ```
 *
 * ## Creating the API handler
 *
 * This example uses github, make sure to set the following environment variables:
 *
 * ```
 * GITHUB_ID=your_github_oauth_id
 * GITHUB_SECRET=your_github_oauth_secret
 * ```
 *
 * ```ts
 * // routes/api/auth/[...solidauth].ts
 * import { SolidAuth, type SolidAuthConfig } from "@auth/solid-start"
 * import GitHub from "@auth/core/providers/github"
 *
 * export const authOpts: SolidAuthConfig = {
 *   providers: [
 *     GitHub({
 *       clientId: process.env.GITHUB_ID,
 *       clientSecret: process.env.GITHUB_SECRET,
 *     }),
 *   ],
 *   debug: false,
 * }
 *
 * export const { GET, POST } = SolidAuth(authOpts)
 * ```
 *
 * ## Getting the current session
 *
 * ```ts
 * import { getSession } from "@auth/solid-start"
 * import { createServerData$ } from "solid-start/server"
 * import { authOpts } from "~/routes/api/auth/[...solidauth]"
 *
 * export const useSession = () => {
 *   return createServerData$(
 *     async (_, { request }) => {
 *       return await getSession(request, authOpts)
 *     },
 *     { key: () => ["auth_user"] }
 *   )
 * }
 *
 * // useSession returns a resource:
 * const session = useSession()
 * const loading = session.loading
 * const user = () => session()?.user
 * ```
 * ## Protected Routes
 *
 * ### When Using SSR
 *
 * When using SSR, it is recommended to create a `Protected` component that will trigger suspense using the `Show` component. It should look like this:
 *
 *
 * ```tsx
 * // components/Protected.tsx
 * import { type Session } from "@auth/core/types";
 * import { getSession } from "@auth/solid-start";
 * import { Component, Show } from "solid-js";
 * import { useRouteData } from "solid-start";
 * import { createServerData$, redirect } from "solid-start/server";
 * import { authOpts } from "~/routes/api/auth/[...solidauth]";
 *
 * const Protected = (Comp: IProtectedComponent) => {
 *   const routeData = () => {
 *     return createServerData$(
 *       async (_, event) => {
 *         const session = await getSession(event.request, authOpts);
 *         if (!session || !session.user) {
 *           throw redirect("/");
 *         }
 *         return session;
 *       },
 *       { key: () => ["auth_user"] }
 *     );
 *   };
 *
 *   return {
 *     routeData,
 *     Page: () => {
 *       const session = useRouteData<typeof routeData>();
 *       return (
 *         <Show when={session()} keyed>
 *           {(sess) => <Comp {...sess} />}
 *         </Show>
 *       );
 *     },
 *   };
 * };
 *
 * type IProtectedComponent = Component<Session>;
 *
 * export default Protected;
 * ```
 *
 * It can be used like this:
 *
 *
 * ```tsx
 * // routes/protected.tsx
 * import Protected from "~/components/Protected";
 *
 * export const { routeData, Page } = Protected((session) => {
 *   return (
 *     <main class="flex flex-col gap-2 items-center">
 *       <h1>This is a protected route</h1>
 *     </main>
 *   );
 * });
 *
 * export default Page;
 * ```
 *
 * ### When Using CSR
 *
 * When using CSR, the `Protected` component will not work as expected and will cause the screen to flash. To fix this, a Solid-Start middleware is used:
 *
 * ```tsx
 * // entry-server.tsx
 * import { Session } from "@auth/core";
 * import { getSession } from "@auth/solid-start";
 * import { redirect } from "solid-start";
 * import {
 *   StartServer,
 *   createHandler,
 *   renderAsync,
 * } from "solid-start/entry-server";
 * import { authOpts } from "./routes/api/auth/[...solidauth]";
 *
 * const protectedPaths = ["/protected"]; // add any route you wish in here
 *
 * export default createHandler(
 *   ({ forward }) => {
 *     return async (event) => {
 *       if (protectedPaths.includes(new URL(event.request.url).pathname)) {
 *         const session = await getSession(event.request, authOpts);
 *         if (!session) {
 *           return redirect("/");
 *         }
 *       }
 *       return forward(event);
 *     };
 *   },
 *   renderAsync((event) => <StartServer event={event} />)
 * );
 * ```
 *
 * And now a protected route can be created:
 *
 *
 * ```tsx
 * // routes/protected.tsx
 * export default () => {
 *   return (
 *     <main class="flex flex-col gap-2 items-center">
 *       <h1>This is a protected route</h1>
 *     </main>
 *   );
 * };
 * ```
 *
 * :::note
 * The CSR method should also work when using SSR, the SSR method shouldn't work when using CSR
 * :::
 *
 */
export function SolidAuth(config: SolidAuthConfig) {
  const { prefix = "/api/auth", ...authOptions } = config
  authOptions.secret ??= process.env.AUTH_SECRET
  authOptions.trustHost ??= !!(
    process.env.AUTH_TRUST_HOST ??
    process.env.VERCEL ??
    process.env.NODE_ENV !== "production"
  )
  const handler = SolidAuthHandler(prefix, authOptions)
  return {
    async GET(event: any) {
      return await handler(event)
    },
    async POST(event: any) {
      return await handler(event)
    },
  }
}

export type GetSessionResult = Promise<Session | null>

export async function getSession(
  req: Request,
  options: Omit<AuthConfig, "raw">
): GetSessionResult {
  options.secret ??= process.env.AUTH_SECRET
  options.trustHost ??= true

  const url = new URL("/api/auth/session", req.url)
  const response = await Auth(
    new Request(url, { headers: req.headers }),
    options
  )

  const { status = 200 } = response

  const data = await response.json()

  if (!data || !Object.keys(data).length) return null
  if (status === 200) return data
  throw new Error(data.message)
}
