// apps/playground-vite/renderer/footer.tsx
import styles from './footer.module.css'

export default function Footer () {
  return (
    <footer className={styles.footer}>
      <hr />
      <ul className={styles.navItems}>
        <li className={styles.navItem}>
          <a href="https://next-auth.js.org">Documentation</a>
        </li>
        <li className={styles.navItem}>
          <a href="https://www.npmjs.com/package/next-auth">NPM</a>
        </li>
        <li className={styles.navItem}>
          <a href="https://github.com/nextauthjs/next-auth/tree/main/apps/playground-vite">GitHub</a>
        </li>
      </ul>
    </footer>
  )
}

// apps/playground-nuxt/playground/components/Footer.vue
<template>
  <footer class="fotter">
    <hr>
    <ul class="navItems">
      <li class="navItem">
        <a href="https://github.com/nextauthjs/next-auth/tree/main/apps/playground-nuxt">Demo GitHub</a>
      </li>
      <li class="navItem">
        <a href="https://next-auth.js.org">Next.js Documentation</a>
      </li>
    </ul>
  </footer>
</template>

<style>
.footer {
margin-top: 2rem;
}

.navItems {
margin-bottom: 1rem;
padding: 0;
list-style: none;
}

.navItem {
display: inline-block;
margin-right: 1rem;
}
</style>
