// packages/frameworks-sveltekit/src/lib/components/SignOut.svelte
<script lang="ts">
  import { enhance } from "$app/forms"
  import type { signOut } from "$lib/actions"

  export let className = ""
  export let options: Parameters<typeof signOut>[0] = undefined
  export let signOutPage = "signout"
  
</script>

<form
  method="POST"
  action={`/${signOutPage}`}
  use:enhance
  class={`signOutButton ${className}`}
  {...$$restProps}
>
  {#if options}
    {#if options?.redirect}
      <input type="hidden" name="redirect" value={options.redirect} />
    {/if}
    {#if options?.redirectTo}
      <input type="hidden" name="redirectTo" value={options.redirectTo} />
    {/if}
  {/if}
  <slot>
    <button type="submit">
      Sign out
    </button>
  </slot>
</form>

// src/server/pages/signout.tsx
import { h } from 'preact' // eslint-disable-line no-unused-vars
import render from 'preact-render-to-string'

// TODO: normalized options type
export default ({ baseUrl, csrfToken }) => {
  return render(
    <div className='signout'>
      <h1>Are you sure you want to sign out?</h1>
      <form action={`${baseUrl}/signout`} method='POST'>
        <input type='hidden' name='csrfToken' value={csrfToken} />
        <button type='submit'>Sign out</button>
      </form>
    </div>
  )
}
